### ISSUE TITLE
Invalid URL 'None/v2/info': No schema supplied.

### ISSUE THREAD

**Issue by Xhings** [chaostoolkit/chaostoolkit-cloud-foundry#21]
Hi, my setup is throwing below exception, experiment txt is attached. Why is it still picking None/v2/info when I have specified "cf_api_url": "https://api.cffs.test.net", in the experiment.json?
Not sure what I am missing.
```
[exp_org.txt](https://github.com/chaostoolkit-incubator/chaostoolkit-cloud-foundry/files/3303444/exp_org.txt)
[2019-06-18 16:01:05 DEBUG] [__init__:55] Querying a new access token for client 'cf'
[2019-06-18 16:01:05 DEBUG] [activity:226] Activity failed
    Traceback (most recent call last):
      File "c:\myinstalls\python\lib\site-packages\chaoslib\provider\python.py", line 55, in run_python_activity
        return func(**arguments)
      File "c:\myinstalls\python\lib\site-packages\chaoscf\probes.py", line 33, in get_app_stats
        space_name=space_name)
      File "c:\myinstalls\python\lib\site-packages\chaoscf\api.py", line 134, in get_app_by_name
        configuration, secrets, space_name, space_guid, org_name, org_guid)
      File "c:\myinstalls\python\lib\site-packages\chaoscf\api.py", line 103, in _get_filter_query
        org = get_org_by_name(org_name, configuration, secrets)
      File "c:\myinstalls\python\lib\site-packages\chaoscf\api.py", line 63, in get_org_by_name
        "q": "name:{o}".format(o=org_name)}).json()
      File "c:\myinstalls\python\lib\site-packages\chaoscf\api.py", line 25, in call_api
        tokens = auth(configuration, secrets)
      File "c:\myinstalls\python\lib\site-packages\chaoscf\__init__.py", line 57, in auth
        verify_ssl)
      File "c:\myinstalls\python\lib\site-packages\chaoscf\__init__.py", line 67, in get_tokens
        r = requests.get(info_url, verify=verify_ssl)
      File "c:\myinstalls\python\lib\site-packages\requests\api.py", line 75, in get
        return request('get', url, params=params, **kwargs)
      File "c:\myinstalls\python\lib\site-packages\requests\api.py", line 60, in request
        return session.request(method=method, url=url, **kwargs)
      File "c:\myinstalls\python\lib\site-packages\requests\sessions.py", line 519, in request
        prep = self.prepare_request(req)
      File "c:\myinstalls\python\lib\site-packages\requests\sessions.py", line 462, in prepare_request
        hooks=merge_hooks(request.hooks, self.hooks),
      File "c:\myinstalls\python\lib\site-packages\requests\models.py", line 313, in prepare
        self.prepare_url(url, params)
      File "c:\myinstalls\python\lib\site-packages\requests\models.py", line 387, in prepare_url
        raise MissingSchema(error)
    requests.exceptions.MissingSchema: Invalid URL 'None/v2/info': No schema supplied. Perhaps you meant http://None/v2/info?
```

**Comment by Xhings** [comment]
[exp_org.txt](https://github.com/chaostoolkit-incubator/chaostoolkit-cloud-foundry/files/3303457/exp_org.txt)
Experiment JSON attached.

**Comment by Lawouach** [comment]
Hi @Xhings,

Could you try this:

```
{
  "version": "0.1.0",
  "title": "Get PCF App Stats",
  "description": "Get App details",
  "configuration": {
      "cf_api_url": "https://api.cffs.test.net",
      "cf_verify_ssl": false
    },
    "secrets": {
      "cloudfoundry": {
        "cf_username": "username",
        "cf_password": "Passw0rd"
      }
    },
  "steady-state-hypothesis": {
    "title": "Access App details",
    "probes": [
      {
        "type": "probe",
        "name": "fetch-app-statistics",
        "tolerance": true,
        "provider": {
          "type": "python",
          "module": "chaoscf.probes",
          "func": "get_app_stats",
	  "secrets": ["cloudfoundry"],
          "arguments": {
            "app_name": "MyAppName",
            "org_name": "pattar",
            "space_name": "putra"
          }
        }
      }
    ]
  },
  "method": [
    {
      "type": "action",
      "name": "stop an app",
      "provider": {
        "type": "python",
        "module": "chaoscf.probes",
        "func": "get_app_by_name",
	  "secrets": ["cloudfoundry"],
        "arguments": {
          "app_name": "MyAppName",
          "org_name": "pattar",
          "space_name": "putra"
        }
      }
    }
  ],
  "rollbacks": []
}```

The secrets and configiration sections should be set at the top-level of the experiment. The secrets should only be referenced from the provider block.

**Comment by Xhings** [comment]
Got it working thanks @Lawouach .

**Comment by Lawouach** [comment]
Awesome. Enjoy :)
